name: JustinCafiero.com
favicon: null
layout_spectrum: 0
typography_spectrum: 0.43368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111113'
    - '#8d3017'
    - '#cba02f'
    - '#ccbd82'
    - '#485583'
  brandStrength: 0.3696938450448215
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.832579183159396
purpose: []
